### ISSUE TITLE
Nodejs install documentation is not compatible with Windows

### ISSUE THREAD

**Issue by kaiyamag** [pyOpenSci/peer-review-metrics#7]
Step 2 of the README (installing nodejs) uses single quotes around 'nodejs>=20,<21' which is not compatible on Windows. The Windows installation command requires double quotes, e.g., "nodejs>=20,<21"

**Comment by lwasser** [comment]
Thank you for this @kaiyamag this was resolved here https://github.com/pyOpenSci/peer-review-metrics/pull/8 so i'm closing this!! thank you again for the contributions and for joining our sprint!!!
