### ISSUE TITLE
Add more information in the README.md about configuring GitHub token for using pyosMeta.

### ISSUE THREAD

**Issue by ehinman** [pyOpenSci/peer-review-metrics#9]
Currently, developers of the peer-review-metrics repo need to follow the directions for authenticating their GitHub token contained in the pyosMeta repo. This led to some confusion about installing pyosMeta to run peer-review-metrics myst notebook, so this issue suggests adding the configuration instructions to the README.md of the peer-review-metrics repo, as well as an .env-default file as part of the instruction steps.

**Comment by lwasser** [comment]
@ehinman thank you again for this. this was addressed via your pr -- #11 -- i'll close this!!
